[package]
name = "rquant"
version = "0.1.0"
authors = ["Xiaojun Gao <gaoxiaojun@gmail.com>"]

[dependencies]
mio = { git = "https://github.com/carllerche/mio" }
chrono = "0.2"
clippy = { version = "0.0.21", optional = true }


[features]
default = []
dev = ["clippy"]
